// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bus.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Bus.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace BUS {

namespace {

const ::google::protobuf::Descriptor* Bus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Bus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Bus_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Bus_2eproto() {
  protobuf_AddDesc_Bus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Bus.proto");
  GOOGLE_CHECK(file != NULL);
  Bus_descriptor_ = file->message_type(0);
  static const int Bus_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bus, list_),
  };
  Bus_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Bus_descriptor_,
      Bus::default_instance_,
      Bus_offsets_,
      -1,
      -1,
      -1,
      sizeof(Bus),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bus, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bus, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Bus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Bus_descriptor_, &Bus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Bus_2eproto() {
  delete Bus::default_instance_;
  delete Bus_reflection_;
}

void protobuf_AddDesc_Bus_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Bus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tBus.proto\022\003BUS\"\023\n\003Bus\022\014\n\004list\030\001 \001(\tb\006p"
    "roto3", 45);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Bus.proto", &protobuf_RegisterTypes);
  Bus::default_instance_ = new Bus();
  Bus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Bus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Bus_2eproto {
  StaticDescriptorInitializer_Bus_2eproto() {
    protobuf_AddDesc_Bus_2eproto();
  }
} static_descriptor_initializer_Bus_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Bus::kListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Bus::Bus()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:BUS.Bus)
}

void Bus::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Bus::Bus(const Bus& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:BUS.Bus)
}

void Bus::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  list_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Bus::~Bus() {
  // @@protoc_insertion_point(destructor:BUS.Bus)
  SharedDtor();
}

void Bus::SharedDtor() {
  list_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Bus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Bus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Bus_descriptor_;
}

const Bus& Bus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Bus_2eproto();
  return *default_instance_;
}

Bus* Bus::default_instance_ = NULL;

Bus* Bus::New(::google::protobuf::Arena* arena) const {
  Bus* n = new Bus;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Bus::Clear() {
// @@protoc_insertion_point(message_clear_start:BUS.Bus)
  list_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Bus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BUS.Bus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string list = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_list()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->list().data(), this->list().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "BUS.Bus.list"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BUS.Bus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BUS.Bus)
  return false;
#undef DO_
}

void Bus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BUS.Bus)
  // optional string list = 1;
  if (this->list().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->list().data(), this->list().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "BUS.Bus.list");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->list(), output);
  }

  // @@protoc_insertion_point(serialize_end:BUS.Bus)
}

::google::protobuf::uint8* Bus::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:BUS.Bus)
  // optional string list = 1;
  if (this->list().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->list().data(), this->list().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "BUS.Bus.list");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->list(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:BUS.Bus)
  return target;
}

int Bus::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:BUS.Bus)
  int total_size = 0;

  // optional string list = 1;
  if (this->list().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->list());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Bus::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BUS.Bus)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Bus* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Bus>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BUS.Bus)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BUS.Bus)
    MergeFrom(*source);
  }
}

void Bus::MergeFrom(const Bus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BUS.Bus)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.list().size() > 0) {

    list_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.list_);
  }
}

void Bus::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BUS.Bus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Bus::CopyFrom(const Bus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BUS.Bus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Bus::IsInitialized() const {

  return true;
}

void Bus::Swap(Bus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Bus::InternalSwap(Bus* other) {
  list_.Swap(&other->list_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Bus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Bus_descriptor_;
  metadata.reflection = Bus_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Bus

// optional string list = 1;
void Bus::clear_list() {
  list_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Bus::list() const {
  // @@protoc_insertion_point(field_get:BUS.Bus.list)
  return list_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Bus::set_list(const ::std::string& value) {
  
  list_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BUS.Bus.list)
}
 void Bus::set_list(const char* value) {
  
  list_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BUS.Bus.list)
}
 void Bus::set_list(const char* value, size_t size) {
  
  list_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BUS.Bus.list)
}
 ::std::string* Bus::mutable_list() {
  
  // @@protoc_insertion_point(field_mutable:BUS.Bus.list)
  return list_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Bus::release_list() {
  // @@protoc_insertion_point(field_release:BUS.Bus.list)
  
  return list_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Bus::set_allocated_list(::std::string* list) {
  if (list != NULL) {
    
  } else {
    
  }
  list_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), list);
  // @@protoc_insertion_point(field_set_allocated:BUS.Bus.list)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace BUS

// @@protoc_insertion_point(global_scope)
